##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rtqfreel/simantan/
    - cd $DEPLOYPATH
    - /usr/local/bin/php artisan migrate
    - /usr/local/bin/php artisan optimize
